### ISSUE TITLE
Create the additional text (collaborative exercise)

### ISSUE THREAD

**Issue by adekimpianna** [adekimpianna/semantic-layout-collaborative-exercise#1]
> assigned to Yana

__As a site visitor, I want to know who they are__

### Repository

- [x] developed on a branch called `additional-text`

### HTML

- [x] A `article` element ...
- [x] ... with a little info about the team
- [x] ... and class "additional-text"

### CSS

- [x] the "additional-text" class

**Comment by harunaltunhr** [comment]
Fill out it please
