### ISSUE TITLE
CSS: color and style 

### ISSUE THREAD

**Issue by adekimpianna** [adekimpianna/semantic-layout-collaborative-exercise#12]
My friends, **this issue is not a part of branches**, but to discuss about the styles that I did not mention on details on development strategy. I am sorry, but it is a lesson well learnt. 
So here is some issues arisen from our pull request:

1. Main area `section` and `article`: Feruz, Murielle, Yana, Boam
     - background colour: #fafafa
     - text: black (normal)
     - use a thin top and bottom border: 1px solid #eeeeee
     - no `h1`  for the heading please
     - float right: 65%
     - any other styles is up to you, it is your creativity! 
---
2. Side are `aside`: Harun
     - background colour: light grey (Harun has to change his)
     - text: white
     - link colour: white (or anything you like)
     - float right, width 30%
     - any other styles is up to you, it is your creativity!
---
3. Top and Bottom area `header` and `footer`: Miroslav
    - background colour `header1 and `footer` has to be the same colour, what colour? up to you
    - there is gonna be an additional elemet `nav` as per request from Miroslav.
---
4. Documentation `for all element`
Is it possible to all of us, to **screenshot the live page on browser of our work**, and attach it on the pull request as documentations? I saw other people doing that and I find it useful.  
**How to do it?** Go to your index.html of your branch and copy the link on https://htmlpreview.github.io/  
This is how mine (before edit) is looking alike: 
![image](https://user-images.githubusercontent.com/62487749/83429559-7ff15b00-a434-11ea-90f6-6cb7067718d0.png)
---
5. Finishing touch
If needed, I will have to set up the padding, margin etc at the last, when all is done. Because we do not agree on using container for this project.
--- 
Do you have some more idea?  
Please tell us your idea below. Thank you very much!

**Comment by miroslavveljanoski** [comment]
This is a great suggestion @adekimpianna. In the future, we should agree on common things like these in the development strategy. Define the style, especially the color and background color are essential. Also, someone should style the body element with padding and margin in order to be same for everybody. 

The next important thing I think is to decide if we are going to use float, flexbox, or flexbox grid for the layout of the elements. 

Regarding the header and the footer, I'm using the same background color `#3c3e41` which is dark grey and white color for the text.

**Comment by adekimpianna** [comment]
@murvanessa @Feruzteame I saw @Boam1994 have a good **soft background-colour**. Should we use it for main area? Or we leave the background-colour to white?
![image](https://user-images.githubusercontent.com/62487749/83430984-e0819780-a436-11ea-92fc-c5b913c0f64f.png)  
  
I think it match with your colour @miroslavveljanoski   
Boam is using this colour
![image](https://user-images.githubusercontent.com/62487749/83431148-2a6a7d80-a437-11ea-847f-39f8e2c47467.png)

**Comment by harunaltunhr** [comment]
How it looks?
![Aside](https://user-images.githubusercontent.com/62182810/83431230-538b0e00-a437-11ea-91bc-b1c6e4726c08.png)

**Comment by adekimpianna** [comment]
I think it looks great @harunaltunhr !

**Comment by miroslavveljanoski** [comment]
> @murvanessa @Feruzteame I saw @Boam1994 have a good **soft background-colour**. Should we use it for main area? Or we leave the background-colour to white?
> ![image](https://user-images.githubusercontent.com/62487749/83430984-e0819780-a436-11ea-92fc-c5b913c0f64f.png)
> 
> I think it match with your colour @miroslavveljanoski
> Boam is using this colour
> ![image](https://user-images.githubusercontent.com/62487749/83431148-2a6a7d80-a437-11ea-847f-39f8e2c47467.png)

I agree. We can use this background-color for the main area

**Comment by harunaltunhr** [comment]
@adekimpianna If ok, Will I merge it?

**Comment by adekimpianna** [comment]
for me it is okay @harunaltunhr wait, we have to wait at least 1 more approve for your pull request 😄

**Comment by Feruzteame** [comment]
hey it looks nice! the main thing is how to collaborate in git-hub. i am totally agree with this issue. thank you  yana. i will do it again depend in this issue.

**Comment by adekimpianna** [comment]
> 
> 
> hey it looks nice! the main thing is how to collaborate in git-hub. i am totally agree with this issue. thank you yana. i will do it again depend in this issue.

yes right it is cool @Feruzteame ! So, what do you think, should we use the background for the main area (section and article) white or colored like Boam? The colour is soft (almost like broken white)
![image](https://user-images.githubusercontent.com/62487749/83431148-2a6a7d80-a437-11ea-847f-39f8e2c47467.png)

**Comment by Feruzteame** [comment]
i think i am not good in design and choose the picture, if you design the web-page it is better to decide it, just tell which color is better and i try to improve it. if you give the chance to pick color kkkkk you will laugh me. sorry dear friend.

**Comment by adekimpianna** [comment]
> 
> 
> i think i am not good in design and choose the picture, if you design the web-page it is better to decide it, just tell which color is better and i try to improve it. if you give the chance to pick color kkkkk you will laugh me. sorry dear friend.

Sorry if I confuse you @Feruzteame , this is a team work and your opinion is also important 🤔  
But if you really want to leave it to my decision, okay, we will use the background colour `#fafafa` and border styles from Boam. Anyway, you are right! The most important thing here is the workflow. Sorry once again.
